name: Build and Push Docker image to Azure Container Registry

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Run az commands
        run: |
          az acr login --name ${{ secrets.REGISTRY_LOGINSERVER }}
          az acr repository list --name ${{ secrets.REGISTRY_LOGINSERVER }} --output table
