name: Build and deploy ASP.Net Core app to Container Apps

on:
  workflow_dispatch:
    inputs:
      useExistingImage:
        description: Use Existing Image
        type: boolean
        required: true
      tagName:
        description: Tag Name
        type: string
        required: true
      containerAppName:
        description: Container App Name
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    if: github.event.inputs.useExistingImage == 'false'
    runs-on: ubuntu-latest

    steps:
      - name: say hello
        run: echo "hello"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: say hello
        run: echo "hello"
