name: job.outputs sample

on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest

    outputs:
      firstword: ${{ steps.step1.outputs.firstword }}
      secondword: ${{ steps.step2.outputs.secondword }}
    
    steps:
      - id: step1
        run: echo "firstword=Hello" >> $GITHUB_OUTPUT
      
      - id: step2
        run: echo "secondword=World" >> $GITHUB_OUTPUT

  test2:
    runs-on: ubuntu-latest
    needs: test1

    steps:
      - run: echo ${{ needs.test1.outputs.firstword }} ${{ needs.test1.outputs.secondword }}
